import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Nav from "/components/nav";
import styles from "../../styles/Contact.module.scss";

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        <h1>Contact</h1>
        <p>
          Jason Lee Wilson
          <br />
          Email:
          <a href="mailto:info@jasonleewilson.com">info@jasonleewilson.com</a>
        </p>
      </main>
    </div>
  );
}
