import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Nav from "/components/nav";
import styles from "../../styles/Skills.module.scss";

export default function Skills() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>
        <h1>Skills</h1>
        <ul>
          <li>HTML</li>
          <li>Javascript</li>
          <li>SCSS</li>
          <li>Components</li>
          <li>UI/UX</li>
          <li>Design</li>
          <li>Pagespeed</li>
          <li>Google Anyltics / GTM</li>
        </ul>
      </main>
    </div>
  );
}
