import type { Metadata } from "next";
import Link from "next/link";
import Icons from "./components/Icons";
// import Image from "next/image";

export const metadata: Metadata = {
  title: "jasonleewilson.com",
  description: "Generated by create next app",
};

import {
  SiTailwindcss,
  SiHtml5,
  SiSass,
  SiCss3,
  SiJavascript,
  SiReact,
  SiFigma,
  SiNextdotjs,
  SiNetlify,
} from "react-icons/si";

export default function Home() {
  return (
    <main className='flex-grow container-fluid bg-gray-100 mt-20 :px-4 lg:px-4'>
      <section className='bg-gray-100 grid h-full place-items-center'>
        <div className='mx-auto max-w-screen-xl px-4'>
          <div className='mx-auto max-w-xl text-center'>
            <h1 className='text-3xl font-extrabold sm:text-5xl'>
              jasonleewilson.
              <strong className='font-extrabold text-primary sm:block'>
                {" "}
                Senior Frontend Engineer.{" "}
              </strong>
            </h1>

            <p className='mt-4 sm:text-xl/relaxed'>
              I build pixel-perfect, engaging, and accessible digital
              experiences.
            </p>

            <div className='mt-8 flex flex-wrap justify-center gap-4'>
              <Link
                className='block w-full rounded bg-primary px-12 py-3 text-sm uppercase font-normal text-white shadow hover:bg-primary focus:outline-none focus:ring active:bg-primary sm:w-auto'
                href='/work'
              >
                View my work
              </Link>

              <Link
                className='block w-full rounded px-12 py-3 text-sm uppercase font-normal text-primary shadow hover:text-primary focus:outline-none focus:ring active:text-primary sm:w-auto'
                href='/about'
              >
                About me
              </Link>
            </div>
            <Icons />
          </div>
        </div>
      </section>
    </main>
  );
}
