import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "jasonleewilson.com - about",
  description: "Generated by create next app",
};

export default function Thankyou() {
  return (
    <>
      <main className=' container mx-auto'>
        <h1 className='text-4xl font-medium text-right mr-2 mb-4'>Thank you</h1>
        <p className='block'>I appreciate you submitting the contact form.</p>
      </main>
    </>
  );
}
