import Head from 'next/head'
// import Image from 'next/image'
import Link from 'next/link'
// import Image from 'next/image'
import Nav from '/components/nav';
import Footer from '/components/footer';
import styles from '../styles/Home.module.scss';
// import styles from '../styles/Nav.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>jasonleewilson.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Image src="/logo.svg" alt="Logo" width={16} height={16} /> */}
      <Nav />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://jasonleewilson.com/">jasonleewilson</a>
        </h1>
      </main>

      <Footer />
    </div>
  )
}
